// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $game from "./routes/game.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $webgl from "./routes/webgl.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FullscreenButton from "./islands/FullscreenButton.tsx";
import * as $GameCanvas from "./islands/GameCanvas.tsx";
import * as $MultiplayerSidebar from "./islands/MultiplayerSidebar.tsx";
import * as $WebGlFullscreenButton from "./islands/WebGlFullscreenButton.tsx";
import * as $WebGlGameCanvas from "./islands/WebGlGameCanvas.tsx";
import * as $webgl_ui_text from "./islands/webgl-ui-text.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/game.ts": $game,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/webgl.tsx": $webgl,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FullscreenButton.tsx": $FullscreenButton,
    "./islands/GameCanvas.tsx": $GameCanvas,
    "./islands/MultiplayerSidebar.tsx": $MultiplayerSidebar,
    "./islands/WebGlFullscreenButton.tsx": $WebGlFullscreenButton,
    "./islands/WebGlGameCanvas.tsx": $WebGlGameCanvas,
    "./islands/webgl-ui-text.ts": $webgl_ui_text,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
