#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

pub mod abi;
pub mod hash;
pub mod input;
pub mod intent;
pub mod keycode;
pub mod replay;
pub mod session;
pub mod world;

pub use abi::{
    DRAWCMD_INSTANCE_COUNT_OFFSET, DRAWCMD_INSTANCE_OFFSET_OFFSET, DRAWCMD_PROGRAM_OFFSET,
    DRAWCMD_PROGRAM_RECT, DRAWCMD_PROGRAM_TEXT, DRAWCMD_RESERVED_OFFSET, DRAWCMD_SCISSOR_H_OFFSET,
    DRAWCMD_SCISSOR_W_OFFSET, DRAWCMD_SCISSOR_X_OFFSET, DRAWCMD_SCISSOR_Y_OFFSET,
    DRAWCMD_SIZE_BYTES, DrawCmd, GLYPH_INSTANCE_ALPHA_OFFSET, GLYPH_INSTANCE_POS_OFFSET,
    GLYPH_INSTANCE_SIZE_OFFSET, GLYPH_INSTANCE_STRIDE_BYTES, GLYPH_INSTANCE_STRIDE_FLOATS,
    GLYPH_INSTANCE_TINT_OFFSET, GLYPH_INSTANCE_UV_OFFSET, GlyphInstance, ProgramId,
    RECT_INSTANCE_ALPHA_OFFSET, RECT_INSTANCE_POS_OFFSET, RECT_INSTANCE_SIZE_OFFSET,
    RECT_INSTANCE_STRIDE_BYTES, RECT_INSTANCE_STRIDE_FLOATS, RECT_INSTANCE_TINT_OFFSET,
    RectInstance,
};
pub use hash::{
    FNV_OFFSET_BASIS, FNV_PRIME, FnvHasher, StateHash, canonicalize_f32, draw_hash,
    draw_state_hash, format_state_hash,
};
pub use replay::{
    WORLD_REPLAY_FORMAT_VERSION, WORLD_SNAPSHOT_ENCODING_VERSION, WorldReplay,
    WorldReplayEvent, WorldReplayIoError, WorldReplayMetadata, WorldReplayRecorder,
    WorldReplayRecorderOptions, encode_world_snapshot_canonical, load_world_replay,
    save_world_replay, world_state_hash,
};
pub use input::{
    EventKind, INPUT_ARENA_EVENTS_OFFSET, INPUT_ARENA_QUEUE_OFFSET, INPUT_ARENA_SAMPLE_OFFSET,
    INPUT_ARENA_SIZE_BYTES, INPUT_EVENT_CODE_OFFSET, INPUT_EVENT_KIND_OFFSET,
    INPUT_EVENT_MODIFIERS_OFFSET, INPUT_EVENT_SIZE_BYTES, INPUT_EVENT_VALUE_OFFSET,
    INPUT_KIND_BLUR, INPUT_KIND_COMPOSITION, INPUT_KIND_KEY_DOWN, INPUT_KIND_KEY_UP,
    INPUT_KIND_RESYNC, INPUT_KIND_TEXT, INPUT_KIND_UNKNOWN, INPUT_MODIFIER_ALT,
    INPUT_MODIFIER_CTRL, INPUT_MODIFIER_META, INPUT_MODIFIER_SHIFT, INPUT_QUEUE_CAPACITY,
    INPUT_QUEUE_HEADER_COUNT_OFFSET, INPUT_QUEUE_HEADER_OVERFLOW_OFFSET,
    INPUT_QUEUE_HEADER_SIZE_BYTES, INPUT_SAMPLE_BUTTONS_OFFSET, INPUT_SAMPLE_DPR_OFFSET,
    INPUT_SAMPLE_DT_MS_OFFSET, INPUT_SAMPLE_FRAMEBUFFER_H_OFFSET,
    INPUT_SAMPLE_FRAMEBUFFER_W_OFFSET, INPUT_SAMPLE_POINTER_X_OFFSET,
    INPUT_SAMPLE_POINTER_Y_OFFSET, INPUT_SAMPLE_WINDOW_FOCUSED_OFFSET, INPUT_SAMPLED_SIZE_BYTES,
    InputArena, InputEvent, InputQueueHeader, InputSampled,
};
pub use session::{ChatMsg, SessionIntent, SessionModel, TextEdit};
pub use keycode::KeyCode;
pub use world::{
    BlockType, DEFAULT_CHUNK_EDGE, DEFAULT_MOVEMENT_TICKS_PER_TILE, DEFAULT_WORLD_CHUNKS, Dir,
    EntityMovementSnapshot, EntitySnapshot, MoveEntityError, TerrainConfig, Vec3i, Vec3u,
    WorldCommand, WorldCommandError, WorldConfig, WorldIntent, WorldSnapshot,
};
