#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

pub mod abi;

pub use abi::{
    DRAWCMD_INSTANCE_COUNT_OFFSET, DRAWCMD_INSTANCE_OFFSET_OFFSET, DRAWCMD_PROGRAM_OFFSET,
    DRAWCMD_PROGRAM_RECT, DRAWCMD_PROGRAM_TEXT, DRAWCMD_RESERVED_OFFSET, DRAWCMD_SCISSOR_H_OFFSET,
    DRAWCMD_SCISSOR_W_OFFSET, DRAWCMD_SCISSOR_X_OFFSET, DRAWCMD_SCISSOR_Y_OFFSET,
    DRAWCMD_SIZE_BYTES, DrawCmd, GLYPH_INSTANCE_ALPHA_OFFSET, GLYPH_INSTANCE_POS_OFFSET,
    GLYPH_INSTANCE_SIZE_OFFSET, GLYPH_INSTANCE_STRIDE_BYTES, GLYPH_INSTANCE_STRIDE_FLOATS,
    GLYPH_INSTANCE_TINT_OFFSET, GLYPH_INSTANCE_UV_OFFSET, GlyphInstance, ProgramId,
    RECT_INSTANCE_ALPHA_OFFSET, RECT_INSTANCE_POS_OFFSET, RECT_INSTANCE_SIZE_OFFSET,
    RECT_INSTANCE_STRIDE_BYTES, RECT_INSTANCE_STRIDE_FLOATS, RECT_INSTANCE_TINT_OFFSET,
    RectInstance,
};
