/* eslint-disable */
// This file is generated from game_engine/od_core. Do not edit by hand.
export const ABI = Object.freeze({
  DRAWCMD_SIZE_BYTES: 32,
  DRAWCMD_PROGRAM_RECT: 0,
  DRAWCMD_PROGRAM_TEXT: 1,
  DRAWCMD_PROGRAM_OFFSET: 0,
  DRAWCMD_INSTANCE_OFFSET_OFFSET: 4,
  DRAWCMD_INSTANCE_COUNT_OFFSET: 8,
  DRAWCMD_SCISSOR_X_OFFSET: 12,
  DRAWCMD_SCISSOR_Y_OFFSET: 16,
  DRAWCMD_SCISSOR_W_OFFSET: 20,
  DRAWCMD_SCISSOR_H_OFFSET: 24,
  DRAWCMD_RESERVED_OFFSET: 28,
  RECT_INSTANCE_STRIDE_FLOATS: 8,
  RECT_INSTANCE_STRIDE_BYTES: 32,
  RECT_INSTANCE_POS_OFFSET: 0,
  RECT_INSTANCE_SIZE_OFFSET: 8,
  RECT_INSTANCE_TINT_OFFSET: 16,
  RECT_INSTANCE_ALPHA_OFFSET: 28,
  GLYPH_INSTANCE_STRIDE_FLOATS: 12,
  GLYPH_INSTANCE_STRIDE_BYTES: 48,
  GLYPH_INSTANCE_POS_OFFSET: 0,
  GLYPH_INSTANCE_SIZE_OFFSET: 8,
  GLYPH_INSTANCE_UV_OFFSET: 16,
  GLYPH_INSTANCE_TINT_OFFSET: 32,
  GLYPH_INSTANCE_ALPHA_OFFSET: 44,
} as const);
export type DrawCmdProgram = typeof ABI.DRAWCMD_PROGRAM_RECT | typeof ABI.DRAWCMD_PROGRAM_TEXT;
