set -euo pipefail;
echo Importing game_library/assets/;
rm -rf static/assets;
mkdir -p static/assets;
cp -R game_library/assets/. static/assets/;
echo Building rust project;
cargo build --manifest-path game_library/Cargo.toml --release --target wasm32-unknown-unknown --no-default-features --features web;
echo Compiling wasm library;
wasm-bindgen --target web --out-dir static/game game_library/target/wasm32-unknown-unknown/release/open_dwarf_lib.wasm;
echo Optimizing wasm size;
wasm-opt -Oz --strip-debug static/game/open_dwarf_lib_bg.wasm -o static/game/opt_open_dwarf_lib.wasm --enable-bulk-memory-opt --enable-sign-ext --enable-nontrapping-float-to-int;
echo Compressing wasm to Brotli file;
brotli -q 11 static/game/opt_open_dwarf_lib.wasm -f -o static/game/opt_open_dwarf_lib.wasm.br;
echo Done 😎;
notify-send -i game_library/assets/sprites/Dwarf.png "OpenDwarf" "web-release complete";
