import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const STAGE = 1;
const CHECKPOINT =
  "docs/design/checkpoints/engine-render-hot-path-stage-1.json";
const EVIDENCE_DIR = "docs/design/checkpoints/evidence";
const SNAPSHOT_REPORT =
  `${EVIDENCE_DIR}/engine-render-hot-path-stage-1-debug.json`;
const PERF_REPORT = `${EVIDENCE_DIR}/engine-render-hot-path-stage-1-perf.json`;
const PROFILE_REPORT =
  `${EVIDENCE_DIR}/engine-render-hot-path-stage-1-profile.json`;

type CommandRecord = {
  command: string;
  status: "PASS";
  failed: 0;
  evidence: string;
};

type ProfileRoute = {
  samples: number[];
  medianMs: number;
  p95Ms: number;
  gl: {
    vendor: string;
    renderer: string;
    rendererSource: string;
    errors: number[];
    contextLost: boolean;
  };
};

async function run(
  command: string,
  args: string[],
  label: string,
  env: Record<string, string> = {},
): Promise<CommandRecord> {
  console.log(`\n==> ${label}`);
  const child = new Deno.Command(command, {
    args,
    env,
    stdout: "inherit",
    stderr: "inherit",
  }).spawn();
  const status = await child.status;
  if (!status.success) {
    throw new Error(`${label} failed with exit code ${status.code}`);
  }
  return {
    command: label,
    status: "PASS",
    failed: 0,
    evidence: "generated by engine:accept-stage1",
  };
}

async function git(args: string[]) {
  const output = await new Deno.Command("git", {
    args,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!output.success) {
    throw new Error(new TextDecoder().decode(output.stderr));
  }
  return new TextDecoder().decode(output.stdout).trim();
}

async function sha256(path: string) {
  return createHash("sha256").update(await readFile(path)).digest("hex");
}

async function readJson(path: string) {
  return JSON.parse(await Deno.readTextFile(path));
}

async function artifact(profile: "debug" | "release", servedSha256: string) {
  const metadata = await readJson("engine/generated/od_wasm.build.json");
  if (metadata.profile !== profile) {
    throw new Error(`expected ${profile} metadata, got ${metadata.profile}`);
  }
  const generatedSha256 = await sha256("engine/generated/od_wasm_bg.wasm");
  const staticSha256 = await sha256("static/engine/od_wasm_bg.wasm");
  if (
    generatedSha256 !== metadata.wasm.sha256 ||
    staticSha256 !== metadata.wasm.sha256 ||
    servedSha256 !== metadata.wasm.sha256
  ) {
    throw new Error(
      `${profile} generated/static/metadata/served hashes disagree`,
    );
  }
  return {
    profile,
    metadataPath: "engine/generated/od_wasm.build.json",
    generatedSha256,
    staticSha256,
    servedSha256,
  };
}

await mkdir(EVIDENCE_DIR, { recursive: true });

const commands: CommandRecord[] = [];
commands.push(
  await run("deno", ["task", "engine:test"], "deno task engine:test"),
);
commands.push(
  await run("deno", ["task", "engine:check"], "deno task engine:check"),
);
commands.push(
  await run("deno", ["task", "engine:dev"], "deno task engine:dev"),
);
commands.push(await run("deno", ["task", "unit"], "deno task unit"));
commands.push(
  await run(
    "bash",
    ["-lc", "npx playwright test tests/engine*.test.ts --workers=1"],
    "npx playwright test tests/engine*.test.ts --workers=1",
    {
      ENGINE_EXPECTED_PROFILE: "debug",
      ENGINE_SNAPSHOT_REPORT_PATH: SNAPSHOT_REPORT,
    },
  ),
);

const snapshot = await readJson(SNAPSHOT_REPORT);
const debugArtifact = await artifact("debug", snapshot.artifact.servedSha256);

commands.push(
  await run(
    "deno",
    ["task", "engine:test-perf-browser"],
    "deno task engine:test-perf-browser",
    { ENGINE_PERF_REPORT_PATH: PERF_REPORT },
  ),
);
const perf = await readJson(PERF_REPORT);

commands.push(
  await run(
    "deno",
    ["task", "engine:perf"],
    "deno task engine:perf",
    { ENGINE_PERF_OUTPUT: PROFILE_REPORT },
  ),
);
const profile = await readJson(PROFILE_REPORT);
const releaseArtifact = await artifact(
  "release",
  profile.results["/engine"].provenance.served.sha256,
);

const goldenFiles = (await git([
  "ls-files",
  "tests/goldens",
  "game_engine/od_ui/goldens",
  "game_engine/od_world/goldens",
]))
  .split("\n").filter(Boolean).sort();
const changedGoldens = (await git([
  "diff",
  "--name-only",
  "--",
  "tests/goldens",
  "game_engine/od_ui/goldens",
  "game_engine/od_world/goldens",
]))
  .split("\n").filter(Boolean);
if (changedGoldens.length > 0) {
  throw new Error(
    `goldens changed without authorization: ${changedGoldens.join(", ")}`,
  );
}
const goldenSha256ByFile = Object.fromEntries(
  await Promise.all(
    goldenFiles.map(async (path) => [path, await sha256(path)]),
  ),
);

const route = (value: ProfileRoute) => ({
  samplesMs: value.samples,
  medianMs: value.medianMs,
  p95Ms: value.p95Ms,
  gl: {
    vendor: value.gl.vendor,
    renderer: value.gl.renderer,
    rendererSource: value.gl.rendererSource,
    errors: value.gl.errors,
    contextLost: value.gl.contextLost,
  },
});

const head = await git(["rev-parse", "HEAD"]);
const digestOutput = await new Deno.Command("deno", {
  args: [
    "task",
    "engine:validate-hot-path-checkpoint",
    "--print-content-sha",
    "--stage",
    String(STAGE),
  ],
  stdout: "piped",
  stderr: "inherit",
}).output();
if (!digestOutput.success) {
  throw new Error("failed to compute repository content digest");
}
const contentSha256 = new TextDecoder().decode(digestOutput.stdout).trim()
  .split("\n").at(-1)!;

const checkpoint = {
  schemaVersion: 1,
  stage: STAGE,
  status: "PASS",
  generatedBy: "deno task engine:accept-stage1",
  reviewedImplementation: {
    mode: "content",
    head,
    workspaceDiffSha256: null,
    contentSha256,
  },
  artifacts: { debug: debugArtifact, release: releaseArtifact },
  environment: profile.viewport
    ? { chromium: profile.chromium, viewport: profile.viewport }
    : undefined,
  commands,
  snapshotCalls: snapshot.snapshotCalls,
  snapshotEvidencePath: SNAPSHOT_REPORT,
  harnessPerformance: { ...perf, artifactPath: PERF_REPORT },
  sameRunProfile: {
    artifactPath: PROFILE_REPORT,
    webgl: route(profile.results["/webgl"]),
    engine: route(profile.results["/engine"]),
  },
  goldens: {
    changedFiles: [],
    reason: "No golden files changed or blessed.",
    sha256ByFile: goldenSha256ByFile,
  },
  authorizedDeferrals: [],
  residualRisks: [
    "Stage 1 intentionally retains the legacy renderer snapshot; Stage 2 changes storage only.",
  ],
};

await writeFile(CHECKPOINT, `${JSON.stringify(checkpoint, null, 2)}\n`);
await run(
  "deno",
  ["task", "engine:validate-hot-path-checkpoint", "--stage", String(STAGE)],
  "deno task engine:validate-hot-path-checkpoint --stage 1",
);
console.log(`\nStage 1 acceptance complete: ${CHECKPOINT}`);
