[package]
name = "open_dwarf_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "open_dwarf_native"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.18", default-features = false }
getrandom = { version = "0.3.4", features = ["wasm_js"] }
rand = "0.9.2"
rand_chacha = "0.9.0"
wasm-bindgen = "0.2.106"
image = { version = "0.25.9", default-features = false, features = ["png"] }
base64 = "0.22.1"
flate2 = { version = "1.0.35", default-features = false, features = ["rust_backend"] }
js-sys = "0.3.76"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
wasm-bindgen-futures = "0.4.49"
web-sys = { version = "0.3.76", features = [
  "Clipboard",
  "Crypto",
  "Event",
  "MessageEvent",
  "Navigator",
  "RtcConfiguration",
  "RtcDataChannel",
  "RtcDataChannelInit",
  "RtcIceGatheringState",
  "RtcIceServer",
  "RtcPeerConnection",
  "RtcSdpType",
  "RtcSessionDescription",
  "RtcSessionDescriptionInit",
  "Window",
  "console",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rtc = "0.8.5"
shared = { package = "rtc-shared", version = "0.8.5" }
bytes = "1.11.0"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }

[dev-dependencies]
bacon = "3.20.1"

[features]
default = ["native"]
core = [
  "bevy/asset_processor",
  "bevy/async_executor",
  "bevy/bevy_core_pipeline",
  "bevy/bevy_image",
  "bevy/bevy_log",
  "bevy/bevy_render",
  "bevy/bevy_sprite",
  "bevy/bevy_sprite_render",
  "bevy/bevy_text",
  "bevy/bevy_ui",
  "bevy/bevy_ui_render",
  "bevy/default_font",
  "bevy/multi_threaded",
  "bevy/png",
  "bevy/trace",
]
native = ["bevy/wayland", "core", "bevy/debug"]
web = ["bevy/bevy_winit", "bevy/web", "bevy/webgl2", "core"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
strip = "symbols"
lto = true
panic = "abort"
incremental = true
codegen-units = 1
